# Generated by Django 3.2 on 2023-07-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_certificate_and_filepath_in_filmwork_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(db_index=True, null=True, verbose_name='creation_date'),
        ),
    ]
