repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude_types: [xml]
      - id: no-commit-to-branch
        args: [ --branch=master, --branch=release ]W
  - repo: https://github.com/PyCQA/isort
    rev: ''
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: ''
    hooks:
      - id: flake8
