version: "3.9"

services:
  proxy:
    image: nginx:1.25
    volumes:
      - ./static:/static:ro
      - ./nginx/proxy.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/django_movies.conf:/etc/nginx/sites-available/django_movies.conf
    ports:
      - "8000:80"
    expose:
      - "80"
    depends_on:
      - django_movies

  django_movies:
    volumes:
      - ./static:/app/static
    build:
      context: ./
      dockerfile: ./movies_admin/Dockerfile
    env_file:
    - ./.env
    expose:
      - "9090"
    depends_on:
      - psql_movies

  psql_movies:
    image: postgres:13
    volumes:
      - psql_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    env_file:
    - ./.env
    expose:
      - "5432"
    ports:
    - "5432:5432"

  es_movies:
    image: elasticsearch:8.8.1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "xpack.security.enabled=false"

  redis_movies:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    ports:
      - "6379:6379"

  # TEST NOW
  # etl_movies:
  #   build:
  #     context: ./
  #     dockerfile: ./postgres_to_es/Dockerfile
  #   env_file:
  #   - ./.env
  #   depends_on:
  #     - redis_movies
  #     - psql_movies
  #     - es_movies

volumes:
  elastic_data:
  redis_data:
  psql_data:
